### ISSUE TITLE
The startup scripts need to output data in the new dict format

### ISSUE THREAD

**Issue by ltratt** [softdevteam/warmup_experiment#181]
At the moment (after the merger of #180) I get this exception:

```
make[1]: Leaving directory '/home/ltratt/warmup_experiment/benchmarks'
python2.7 krun/krun.py startup.krun
[2016-10-05 17:36:24: INFO] Wait 60 secs to allow system to cool prior to collecting initial temperature readings
Traceback (most recent call last):
  File "krun/krun.py", line 346, in <module>
    main(parser)
  File "krun/krun.py", line 209, in main
    inner_main(mailer, config, args)
  File "krun/krun.py", line 295, in inner_main
    sanity_checks(config, platform)
  File "krun/krun.py", line 68, in sanity_checks
    vm_info["vm_def"].sanity_checks()
  File "/home/ltratt/warmup_experiment/krun/krun/vm_defs.py", line 633, in sanity_checks
    self._check_truffle_enabled()
  File "/home/ltratt/warmup_experiment/krun/krun/vm_defs.py", line 629, in _check_truffle_enabled
    "jruby_check_graal_enabled.rb", force_dir=VM_SANITY_CHECKS_DIR)
  File "/home/ltratt/warmup_experiment/krun/krun/util.py", line 250, in spawn_sanity_check
    _ = check_and_parse_execution_results(stdout, stderr, rc)
  File "/home/ltratt/warmup_experiment/krun/krun/util.py", line 216, in check_and_parse_execution_results
    key_set = set(json_data.keys())
AttributeError: 'list' object has no attribute 'keys'
Makefile:58: recipe for target 'bench-startup-no-reboots' failed
make: *** [bench-startup-no-reboots] Error 1
bencher3%
```

**Comment by vext01** [comment]
And some need to use the new libkrun API.

**Comment by ltratt** [comment]
OK, so Sarah's going to look at this one. There are two main issues:
- I fixed the statically typed languages to use Krun's new API for getting times, but haven't done so for the dynamically typed languages.
- The startup scripts need to output data in Krun's new format.
