### ISSUE TITLE
Plot script broken

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#187]
```
vext01@bencher3:~/research/warmup_experiment$ ./bin/plot_krun_results rk_results.json.bz2 
Using matplotlib version 1.4.2 with backend TkAgg
Charting with sliding window size: 200, xlimits: None
Loading: rk_results.json.bz2
Traceback (most recent call last):
  File "./bin/plot_krun_results", line 847, in <module>
    options.changepoints)
  File "./bin/plot_krun_results", line 560, in get_data_dictionaries
    for key in data['data']:
KeyError: 'data'
```

**Comment by snim2** [comment]
I'm closing this Issue. `master` branch is not up to date with `master` on Krun because there were a few features I needed to test for which I only had test data with the old JSON keys. PR #162 brings the plotting script (and all the other scripts) up to date.
