### ISSUE TITLE
csv_to_krun doesn't output new Krun tags 

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#202]
Raised by @ltratt 

I think csv_to_krun needs updating?

``` sh
$ bin/csv_to_krun_json -u "`uname -a`" -v HotSpot -l Java dacapo.hotspot.results
$ bin/plot_krun_results dacapo.hotspot.json.bz2
Using matplotlib version 1.4.2 with backend TkAgg
Charting with sliding window size: 200, xlimits: None
Loading: dacapo.hotspot.json.bz2
Traceback (most recent call last):
  File "bin/plot_krun_results", line 1006, in <module>
    options.changepoints)
  File "bin/plot_krun_results", line 713, in get_data_dictionaries
    data_dictionary['cycles_data'][key][machine] = data['core_cycle_counts'][key]
KeyError: 'core_cycle_counts'
```

**Comment by snim2** [comment]
`csv_to_krun_json` definitely does have that key (see below). Can you make sure your copy of warmup is up to date with master and try again?

``` python
def main(in_files, language, vm, uname):
    for filename in in_files:
        data_dictionary = { 'wallclock_times': dict(), # Measurement data.
                   'core_cycles_data': dict(), 'aperf_data': dict(), 
                  'mperf_data': dict(), 'instr_data': dict(), 
                  'audit': dict(), 'config': '', 'reboots': 0, 
                  'starting_temperatures': list()',  'eta_estimates': list(), 
                  'error_flag': list(), }
```
