### ISSUE TITLE
Plot script crashes if a benchmark crashed.

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#265]
I set one pexec's results (wct, and performance counters) to the empty list to emulate a crashed benchmark:

```
$ python -mpdb ~/research/warmup_experiment/bin/plot_krun_results xxx_results.json.bz2 -b "bencher3:binarytrees:Hotspot:default-java:0" -b "bencher3:binarytrees:Hotspot:default-java:1" -o mis.pdf
[2] > /home/vext01/research/warmup_experiment/bin/plot_krun_results(4)<module>()
-> """
(Pdb++) c                                                                                                /home/vext01/.local/lib/python2.7/site-packages/matplotlib/__init__.py:878: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
Saving results to: mis.pdf
Using matplotlib version 1.5.3 with backend agg
Charting with sliding window size: 200, xlimits: None
Loading: xxx_results.json.bz2
Collecting instrumentation data for xxx_results.json.bz2 from xxx_instr_data.
WARNING: Skipping: binarytrees:Hotspot:default-java from bencher3 (benchmark crashed)
Saved: mis.pdf
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/vext01/research/warmup_experiment/bin/plot_krun_results", line 4, in <module>
    """
  File "/home/vext01/research/warmup_experiment/bin/plot_krun_results", line 240, in main
    bmark, vm, mc = all_subplot_titles[index][0].split(', ')[:3]
IndexError: list index out of range
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
[5] > /home/vext01/research/warmup_experiment/bin/plot_krun_results(240)main()
-> bmark, vm, mc = all_subplot_titles[index][0].split(', ')[:3]
(Pdb++) bt                                                                                               
[0]   /usr/lib/python2.7/pdb.py(1314)main()
-> pdb._runscript(mainpyfile)
[1]   /usr/lib/python2.7/pdb.py(1233)_runscript()
-> self.run(statement)
[2]   /usr/lib/python2.7/bdb.py(400)run()
-> exec cmd in globals, locals
[3]   <string>(1)<module>()
[4]   /home/vext01/research/warmup_experiment/bin/plot_krun_results(4)<module>()
-> """
[5] > /home/vext01/research/warmup_experiment/bin/plot_krun_results(240)main()
-> bmark, vm, mc = all_subplot_titles[index][0].split(', ')[:3]
(Pdb++) all_subplot_titles                                                                               
[[]]
```

**Comment by snim2** [comment]
`get_data_dictionaries` correctly skips crashed benchmarks, but the `main` and the plotting functions do not look for `None`s in the list of lists of wallclock times. We don't want to skip a crashed benchmark entirely, because the plot titles need to contain the correct process exec number.

**Comment by vext01** [comment]
Ah, so maybe i was wrong to put empty lists into the readings, it should be a None?

**Comment by snim2** [comment]
A `None` or an empty list should look the same, I think the problem is that `main()` and the other functions do not have an `if/else` to check that they are getting lists of real data.
