### ISSUE TITLE
Crash in plot script using -b

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#303]
```
$ python2.7 ../bin/plot_krun_results -b bencher3:fasta:Graal:default-java:0 -o out/10_classic1.pdf warmup_results_0_7_linux1_i7_4790k.json.bz2 warmup_results_0_7_openbsd1_i7_4790.json.bz2
/home/vext01/.local/lib/python2.7/site-packages/matplotlib/__init__.py:878: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
Saving results to: out/10_classic1.pdf
Using matplotlib version 1.5.3 with backend agg
Charting with sliding window size: 200, xlimits: None
Loading: warmup_results_0_7_linux1_i7_4790k.json.bz2
No VM instrumentation data is available.
Adding run sequence to  fasta:Graal:default-java bencher3
Loading: warmup_results_0_7_openbsd1_i7_4790.json.bz2
No VM instrumentation data is available.
Traceback (most recent call last):
  File "../bin/plot_krun_results", line 1260, in <module>
    cycles_ylimits=cycles_ylimits)
  File "../bin/plot_krun_results", line 231, in main
    instr_pages.append(data_dcts['instr_data'][key][machine])
KeyError: 'fasta:Graal:default-java'
```

If you remove the file `warmup_results_0_7_openbsd1_i7_4790.json.bz2` from the invocation, then no crash. I think it's because graal doesn't run on OpenBSD and thus the key is nonexistent for that file.

**Comment by snim2** [comment]
Yes, this script assumes that every file contains the same keys. It also assumes that different files contain data from different machines, which may not be the case.

**Comment by vext01** [comment]
Not sure if #314 fixes this or not.
