### ISSUE TITLE
Dacapo crash on bencher7

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#317]
```
PYTHONPATH=krun/ JAVA_HOME=/home/kruninit/warmup_experiment/work/openjdk/build/linux-x86_64-normal-server-release/images/j2sdk-image LD_LIBRARY_PATH=/home/kruninit/warmup_experiment/work/gcc-inst/lib64 python2.7 extbench/rundacapo.py
graal:
  avrora: 0Traceback (most recent call last):
  File "extbench/rundacapo.py", line 66, in <module>
    main()
  File "extbench/rundacapo.py", line 58, in main
    assert line[index + 2] == "nsec"
AssertionError
Makefile:71: recipe for target 'bench-dacapo' failed
make: *** [bench-dacapo] Error 1
```

Re-running under pdb to inspect the actual output. Watch this space.

**Comment by ltratt** [comment]
I suspect you haven't rebuilt dacapo. `rm extbench/*jar`, then `./build.sh` should update things.

**Comment by vext01** [comment]
oh yeah, doh.

**Comment by vext01** [comment]
This hasn't crashed after the rebuild. Closing.
