### ISSUE TITLE
Plot script crash with multiple -b arguments and no --one-page

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#360]
This is a crash on master, nothing to do with the insets branch:
```
$ python ../warmup_experiment//bin/plot_krun_results --with-changepoint-means --no-zoom --core-cycles 3 --export-size 
5,6 -o examples/new_warmup_no_migrate.pdf -b bencher5:nbody:HHVM:default-php:8 -b bencher5:binarytrees:HHVM:default-ph
p:8 -b bencher5:nbody:PyPy:default-python:8 -b bencher5:fasta:C:default-c:8 -b bencher5:richards:C:default-c:8 -b benc
her5:richards:HHVM:default-php:8 -b bencher5:richards:LuaJIT:default-lua:8 warmup_results_0_8_linux2_i7_4790_outliers_
w200_changepoints.json.bz2
Saving results to: examples/new_warmup_no_migrate.pdf
Using matplotlib version 1.5.3 with backend agg
Charting with sliding window size: 200, xlimits: None
Plotting cycle counts for core(s): 3
Loading: warmup_results_0_8_linux2_i7_4790_outliers_w200_changepoints.json.bz2
No VM instrumentation data is available.
Adding run sequence to  richards:C:default-c bencher5
Adding run sequence to  nbody:PyPy:default-python bencher5
Adding run sequence to  nbody:HHVM:default-php bencher5
WARNING: Skipping: richards:HHVM:default-php from bencher5 (no executions)
Adding run sequence to  binarytrees:HHVM:default-php bencher5
Adding run sequence to  fasta:C:default-c bencher5
Adding run sequence to  richards:LuaJIT:default-lua bencher5
Plotting Linux$_\mathrm{4790}$: Binary Trees (HHVM) on page 01 of 07.
1 plots arranged in 1 rows and 1 columns.
Plotting Linux$_\mathrm{4790}$: Fasta (C) on page 02 of 07.
1 plots arranged in 1 rows and 1 columns.
Plotting Linux$_\mathrm{4790}$: N-Body (HHVM) on page 03 of 07.
1 plots arranged in 1 rows and 1 columns.
Plotting Linux$_\mathrm{4790}$: N-Body (PyPy) on page 04 of 07.
1 plots arranged in 1 rows and 1 columns.
Plotting Linux$_\mathrm{4790}$: Richards (C) on page 05 of 07.
1 plots arranged in 1 rows and 1 columns.
Saved: examples/new_warmup_no_migrate.pdf
Traceback (most recent call last):
  File "../warmup_experiment//bin/plot_krun_results", line 1404, in <module>
    cycles_ylimits=cycles_ylimits)
  File "../warmup_experiment//bin/plot_krun_results", line 265, in main
    bmark, vm, mc = all_subplot_titles[index][0].split(', ')[:3]
IndexError: list index out of range
```

**Comment by snim2** [comment]
Interesting. One way to "fix" this is to pass in `--one-page` on the command line, in which case you get this (on your fix-xlimits branch): [new_warmup_no_migrate.pdf](https://github.com/softdevteam/warmup_experiment/files/866429/new_warmup_no_migrate.pdf)

Otherwise, the `all_subplot_titles` lists will look like this:

```python
ALL SUBPLOT TITLES: [['Binary Trees, HHVM, Linux$_\\mathrm{4790}$, Proc. exec. #9'], ['Fasta, C, Linux$_\\mathrm{4790}$, Proc. exec. #9'], ['N-Body, HHVM, Linux$_\\mathrm{4790}$, Proc. exec. #9'], ['N-Body, PyPy, Linux$_\\mathrm{4790}$, Proc. exec. #9'], ['Richards, C, Linux$_\\mathrm{4790}$, Proc. exec. #9'], [], ['Richards, LuaJIT, Linux$_\\mathrm{4790}$, Proc. exec. #9']]
```

and you get the traceback above when `index == 5`, due to the empty list. I'll take a closer look later.

**Comment by snim2** [comment]
I've had another look, this is the list of benchmarks you requested:

  * bencher5:nbody:HHVM:default-php:8
  * bencher5:binarytrees:HHVM:default-php:8
  * bencher5:nbody:PyPy:default-python:8
  * bencher5:fasta:C:default-c:8
  * bencher5:richards:C:default-c:8
  * **bencher5:richards:HHVM:default-php:8**
  * bencher5:richards:LuaJIT:default-lua:8

The emboldened benchmark is the one causing the crash, because we skip that benchmark in the warmup experiment, so there is no data for it. 

I'll add some code to print a more sensible warning to the user and assign you.

**Comment by vext01** [comment]
I've just independently debugged the code and come to the same conclusion!
