### ISSUE TITLE
-m and -t are not compatible with --xlimits

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#364]
For example:

```bash
$ ../bin/plot_krun_results --with-changepoint-means --with-outliers -o test.pdf warmup_results.json.b2 --inset-xlimits 50,100 --xlimits 20,200 -m -t
...
Traceback (most recent call last):
  File "../bin/plot_krun_results", line 1435, in <module>
    inset_xlimits=options.inset_xlimits)
  File "../bin/plot_krun_results", line 305, in main
    core_cycles, cycles_ylimits, inset_xlimits)
  File "../bin/plot_krun_results", line 846, in draw_page
    p_exec_charts[index].plot_stack()
  File "../bin/plot_krun_results", line 446, in plot_stack
    self.plot_wallclock_times()
  File "../bin/plot_krun_results", line 500, in plot_wallclock_times
    self.plot_median(self.wallclock_axis)
  File "../bin/plot_krun_results", line 515, in plot_median
    linewidth=LINE_WIDTH, color=MEDIAN_COLOUR)
  File "/home/snim2/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)
  File "/home/snim2/.local/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1406, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/home/snim2/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 407, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/home/snim2/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 385, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/home/snim2/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 244, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (180,) and (160,)
```

**Comment by snim2** [comment]
Moving to stats repo
