### ISSUE TITLE
plot script crash

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#372]
```
arrakis:warmup_experiment> ./bin/plot_krun_results -b bencher5:binarytrees:HHVM:default-php:0 warmup_results_0_8_linux2_i7_4790_outliers_w200_changepoints.json.bz2
Using matplotlib version 1.5.3 with backend TkAgg
Charting with sliding window size: 200, xlimits: None
Loading: warmup_results_0_8_linux2_i7_4790_outliers_w200_changepoints.json.bz2
No VM instrumentation data is available.
Adding run sequence to  binarytrees:HHVM:default-php bencher5
Plotting Linux$_\mathrm{4790}$: Binary Trees (HHVM) on page 01 of 01.
1 plots arranged in 1 rows and 1 columns.
Traceback (most recent call last):
  File "./bin/plot_krun_results", line 1560, in <module>
    inset_xlimits=options.inset_xlimits)
  File "./bin/plot_krun_results", line 316, in main
    core_cycles, cycles_ylimits, inset_xlimits)
  File "./bin/plot_krun_results", line 926, in draw_page
    tukey, core_cycles, cycles_ylimits, inset_x_bounds))
  File "./bin/plot_krun_results", line 360, in __init__
    self.changepoint_means = [changepoint_means[0]]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by snim2** [comment]
OK, fix coming

**Comment by vext01** [comment]
thanks :)
