### ISSUE TITLE
Plotting instrumenation data broken

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#386]
```
Traceback (most recent call last):
  File "../../bin/plot_krun_results", line 1565, in <module>
    inset_xlimits=options.inset_xlimits)
  File "../../bin/plot_krun_results", line 317, in main
    core_cycles, cycles_ylimits, inset_xlimits)
  File "../../bin/plot_krun_results", line 932, in draw_page
    p_exec_charts[index].plot_stack()
  File "../../bin/plot_krun_results", line 484, in plot_stack
    self.plot_instr_data()
  File "../../bin/plot_krun_results", line 682, in plot_instr_data
    legend_texts.add(self.instr_data[index].legend_text)
AttributeError: 'numpy.ndarray' object has no attribute 'legend_text'
```

I'll fix this one.

**Comment by vext01** [comment]
(If I can -- @snim2 any tips you have are welcome ;) )
