### ISSUE TITLE
build_stats does not work on bencher8

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#413]
```
Collecting rpy2
Collecting singledispatch (from rpy2)
  Using cached singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting six (from rpy2)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, singledispatch, rpy2
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

/cc @vext01

**Comment by vext01** [comment]
Our stuff only really works on Debian 8. Bencher 8 is Debian 9.

rmsr for example, is also broken on Debian 9 due to kernel versions.

I think we should track the latest Debian release, but probably not until the camera ready version of the warmup paper is submitted.

**Comment by vext01** [comment]
Maybe this helps?

https://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install

**Comment by snim2** [comment]
It's really only the stats stuff I was trying to get working, not Krun, but at some point we will need both on bencher8. That SO link looks interesting, I'll have a closer look later on; thanks.

**Comment by vext01** [comment]
OK, good luck.

**Comment by snim2** [comment]
This script has moved repo, and now works on Bencher 8.
