### ISSUE TITLE
Tabling dacapo crash

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#449]
```
vext01@debian8:~/research/warmup_experiment$ make tables-dacapo-results                                                                                                                                              
python -m pdb warmup_stats/bin/table_classification_summaries_others -s 2 -o dacapo.table dacapo.graal_outliers_w200_changepoints.json.bz2 dacapo.hotspot_outliers_w200_changepoints.json.bz2
> /home/vext01/research/warmup_experiment/warmup_stats/bin/table_classification_summaries_others(42)<module>()
-> """
(Pdb) c
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "warmup_stats/bin/table_classification_summaries_others", line 42, in <module>
    """
  File "/home/vext01/research/warmup_experiment/warmup_stats/warmup/krun_results.py", line 162, in parse_krun_file_with_changepoints
    machine_name = data['audit']['uname'].split(' ')[1]
IndexError: list index out of range
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/vext01/research/warmup_experiment/warmup_stats/warmup/krun_results.py(162)parse_krun_file_with_changepoints()
-> machine_name = data['audit']['uname'].split(' ')[1]
(Pdb) data['audit']['uname']
u''
```

**Comment by vext01** [comment]
The reason for this is that `csv_to_krun_json` in the `warmup_stats` repo allows running without `--uname` and `--vm` which are needed by the table script `table_classification_summaries_others`.

Should we make those arguments mandatory @snim2?

**Comment by snim2** [comment]
We probably should, thanks.

**Comment by snim2** [comment]
We check CLI options in `warmup_stats` quite carefully now, so this can be closed.
